### ISSUE TITLE
RNASeq pipeline without running STAR?

### ISSUE THREAD

**Issue by pjaborges** [BIMSBbioinfo/pigx#19]
Hi there!

I have been trying to setup RNAseq pipeline to run without using STAR for indexing and so far I was not able to figure it out.

The main reason is that for my purposes I just need to use SALMON. 
Additionally, when using STAR the pipeline always falls into RAM memory issues and I have tried all the possible parameters to limit the amount used. I have 32Gb RAM and is not sufficient (Mouse as model). Also, I cannot use any other machine/cluster with higher RAM capacity.

Given this, I am wondering the following:
1. Is possible to disable STAR? If so, how to do it?
2. By disabling STAR will this affect the outputs generated by the pipeline?

Thank you.
Paulo

**Comment by rekado** [comment]
Hi Paulo,

the RNAseq pipeline can now use Hisat instead of STAR, requiring much less RAM.

~~ Ricardo
